/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArIndexRouteImport } from './routes/ar.index'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as ArConditionsSlugRouteImport } from './routes/ar.conditions.$slug'
import { Route as EnConditionsSlugRouteImport } from './routes/en.conditions.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArIndexRoute = ArIndexRouteImport.update({
  id: '/ar/',
  path: '/ar/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArConditionsSlugRoute = ArConditionsSlugRouteImport.update({
  id: '/ar/conditions/$slug',
  path: '/ar/conditions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnConditionsSlugRoute = EnConditionsSlugRouteImport.update({
  id: '/en/conditions/$slug',
  path: '/en/conditions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ar/': typeof ArIndexRoute
  '/en/': typeof EnIndexRoute
  '/ar/conditions/$slug': typeof ArConditionsSlugRoute
  '/en/conditions/$slug': typeof EnConditionsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ar': typeof ArIndexRoute
  '/en': typeof EnIndexRoute
  '/ar/conditions/$slug': typeof ArConditionsSlugRoute
  '/en/conditions/$slug': typeof EnConditionsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ar/': typeof ArIndexRoute
  '/en/': typeof EnIndexRoute
  '/ar/conditions/$slug': typeof ArConditionsSlugRoute
  '/en/conditions/$slug': typeof EnConditionsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/ar/' | '/en/' | '/ar/conditions/$slug' | '/en/conditions/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ar' | '/en' | '/ar/conditions/$slug' | '/en/conditions/$slug'
  id:
    | '__root__'
    | '/'
    | '/ar/'
    | '/en/'
    | '/ar/conditions/$slug'
    | '/en/conditions/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArIndexRoute: typeof ArIndexRoute
  EnIndexRoute: typeof EnIndexRoute
  ArConditionsSlugRoute: typeof ArConditionsSlugRoute
  EnConditionsSlugRoute: typeof EnConditionsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/': {
      id: '/ar/'
      path: '/ar'
      fullPath: '/ar/'
      preLoaderRoute: typeof ArIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/conditions/$slug': {
      id: '/ar/conditions/$slug'
      path: '/ar/conditions/$slug'
      fullPath: '/ar/conditions/$slug'
      preLoaderRoute: typeof ArConditionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/conditions/$slug': {
      id: '/en/conditions/$slug'
      path: '/en/conditions/$slug'
      fullPath: '/en/conditions/$slug'
      preLoaderRoute: typeof EnConditionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArIndexRoute: ArIndexRoute,
  EnIndexRoute: EnIndexRoute,
  ArConditionsSlugRoute: ArConditionsSlugRoute,
  EnConditionsSlugRoute: EnConditionsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
